name   = input    ('Olá, poderia digitar seu nome e pressinar enter ?: ')
age    = input    ('Obrigado '+name+' por estar utilizando nosso Software, por favor introduza sua idade?: ')
weight = input    ('Por favor introduza seu peso (Será Nosso Segredinho ;D): ')
print             ('Obrigado '+name+' por nos passar suas informações para continuarmos.')
print             ('Só para confirmar: ')
print             ('Nome '+name+' Idade: Segredo ;D Peso: Sergredo ;D')
